name: push
on:
  push:
    tags:
      - 'v1.0.*'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Apk
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: my-artifact
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Output artifact ID
      run: |
        echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
        echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app/build/outputs/apk/debug/app-debug.apk
        token: ${{ github.token }}
        generateReleaseNotes: true
